development:
  adapter: postgresql
  database: my_bookshelf_development
  pool: 5
  timeout: 5000
  username: hello
  password: Wetherell


production:
  adapter: postgresql
  database: my_bookshelf_production
  pool: 5
  timeout: 5000

# development:
#   adapter: sqlite3
#   database: db/my_bookshelf_development.sqlite3
#   pool: 5
#   timeout: 5000